name: tests
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v3
      - name: verify code
        run: ls
      - name: build
        run: docker build -f ./client/Dockerfile.dev -t saardagan/react-test ./client
      - name: execute
        run: docker run saardagan/react-test npm test --coverage