name: tests
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v3
      - name: verify code
        run: ls
      - name: build
        run: docker build -f ./client/Dockerfile.dev -t saardagan/react-test ./client
      - name: execute
        run: docker run -e CI=true saardagan/react-test npm test -- --coverage
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: |
            saardagan/multi-client:latest
            saardagan/multi-client:${{github.sha}}
      -
        name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            saardagan/multi-server:latest
            saardagan/multi-server:${{github.sha}}
      -
        name: Build and push worker
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: |
            saardagan/multi-worker:latest
            saardagan/multi-worker:${{github.sha}}

